"""initial

Revision ID: 6717d9a15f4a
Revises:
Create Date: 2025-04-03 16:22:27.659679

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '6717d9a15f4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
